### ISSUE TITLE
Error: rustdoc format v15 is not supported

### ISSUE THREAD

**Issue by velvia** [obi1kenobi/cargo-semver-checks-action#13]
Hi, I'm using this action script in a project with `rust-toolchain` set to 1.63.0, and getting Error: rustdoc format v15 is not supported.  What should I do?

```
Compiling trustfall_rustdoc v0.3.1
584
   Compiling git2 v0.15.0
585
   Compiling crates-index v0.18.9
586
   Compiling cargo-semver-checks v0.12.0
[587](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:591)
    Finished release [optimized] target(s) in 5m 37s
[588](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:592)
  Installing /home/runner/.cargo/bin/cargo-semver-checks
[589](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:593)
   Installed package `cargo-semver-checks v0.12.0` (executable `cargo-semver-checks`)
[590](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:594)
+ cargo semver-checks check-release --current /tmp/current.json --baseline /tmp/baseline.json
[591](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:595)
Error: rustdoc format v15 for file /tmp/baseline.json is not supported
[592](https://github.com/MystenLabs/mysten-infra/actions/runs/3160462909/jobs/5144946004#step:4:596)
Error: Process completed with exit code 1.
```

The project is open source: 
https://github.com/MystenLabs/mysten-infra

Many thanks

**Comment by obi1kenobi** [comment]
Would your project build with Rust 1.64 or 1.65 beta?

The underlying issue is that `cargo-semver-checks` only works with Rust 1.64 or 1.65 beta at the moment. Apologies for the unhelpful error message. It might support a wider range of stable Rust versions in the future, the issue to follow on that is https://github.com/obi1kenobi/cargo-semver-check/issues/132

If your project would build with 1.64, I could expose a config setting to set the `override: true` flag on the Rust setup action and generate rustdoc with 1.64. Would that work for you?

**Comment by obi1kenobi** [comment]
To test it out, could you try swapping in this action configuration temporarily? If it works out, I can merge my draft PR and make the new options generally available:
```yaml
uses: obi1kenobi/cargo-semver-checks-action@3da499f293b342c80411f313cbaad4d5a3ff7cf0
with:
  crate-name: ${{ matrix.package }}
  version-tag-prefix: ${{ matrix.package }}-v
  rust-override: true
```

**Comment by velvia** [comment]
@obi1kenobi thanks I'll try upgrading to 1.64 and swapping in your action

**Comment by velvia** [comment]
@obi1kenobi A coworker fixed it for me by going to nightly, which proves your point that this works with 1.65 beta.  So I think you can go ahead and ship whatever config change is necessary.   I have to think about how to test this out without publishing a new package as that's normally the workflow I have, but pretty sure it will work now.

**Comment by obi1kenobi** [comment]
Sorry, just to confirm: did your coworker use the config settings I added in the action at hash `3da499f293b342c80411f313cbaad4d5a3ff7cf0` or by just installing nightly Rust in a separate action before the `cargo-semver-checks-action@v1` action?

Nightly works *currently* but is not guaranteed to work: the rustdoc format frequently has breaking changes (7 times in the last ~10 weeks) and being on nightly means that it might suddenly be broken if the new nightly happens to make another breaking change. The `cargo-semver-checks` compatibility guarantee covers the current-newest stable and beta, whereas we can't make any compatibility guarantees about nightly since it changes so much (as it's under active development -- this is not a bad thing in general).

I'll keep the `obi1kenobi/cargo-semver-checks-action@v1` action in sync and working with newest stable and beta. If you're able to switch to 1.64 stable (and generally stay on a recent stable) I'd recommend doing that. If not, try the action setup in my last comment and let me know if that worked for you.

**Comment by velvia** [comment]
@obi1kenobi oh just nightly.  I'll heed your warning and upgrade to 1.64 stable, it should be a small PR and will ensure everything works after that.  :)

**Comment by obi1kenobi** [comment]
Great, thanks for confirming and hope it works!

**Comment by velvia** [comment]
@obi1kenobi I have verified that with an upgrade to 1.64 the workflow works fine.  Thanks, closing.
