### ISSUE TITLE
Include `package` and `manifest-path` in the cache key

### ISSUE THREAD

**Issue by mgr0dzicki** [obi1kenobi/cargo-semver-checks-action#37]
Many repositories using `cargo-semver-checks` in multi-crate workspaces run it separately on each crate in a single job (matrix strategy or separate steps), for example:

 - https://github.com/libp2p/rust-libp2p/blob/master/.github/actions/cargo-semver-checks/action.yml
 - https://github.com/ngrok/ngrok-rs/blob/main/.github/workflows/ci.yml#L78-L92
 - https://github.com/risinglightdb/sqllogictest-rs/blob/main/.github/workflows/ci.yml#L60-L76

If we run the action in these repos specifying only the input `package`, the runs for different crates will share the same cache key. This leads to poor results especially if they are executed concurrently - then only the cache of the recently checked crate can be restored. The current solution is to use input `prefix-key` with the same value as `package`, but I think it'd be better if we changed the default behavior of the action. Now it's not so easy to notice that something is going wrong and I think many users can make such a mistake...

I propose to include values of `package` and `manifest-path` in the cache key. The question is - should they be made a part of the default value for `cache-key` input (currently the name of the job) or should they be included in the unmodifiable part of the key (like the versions of `rustc` and `cargo-semver-checks`)?

**Comment by obi1kenobi** [comment]
Nice work! This is exactly the sort of thing I was hoping we'd catch before releasing.

Let's include `package` and a _hash_ of `manifest-path` in the `cache-key` component, which can be overridden by the user. I suggest using a hash of `manifest-path` instead of the whole thing so we have a guaranteed (and hopefully short-ish) length instead of having arbitrarily-long keys.

I trust you'll remember to update the docs accordingly as well.

Again, great work! 🚀
